services:
  db:
    image: postgres:17-alpine
    container_name: plainly_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PLAINLY_API_KEY: ${NEXT_PUBLIC_PLAINLY_API_KEY}
        NEXT_PUBLIC_WEBHOOK_PUBLIC_URL: ${NEXT_PUBLIC_WEBHOOK_PUBLIC_URL}
        NEXT_PUBLIC_PLAINLY_PROJECT_ID: ${NEXT_PUBLIC_PLAINLY_PROJECT_ID}
    env_file:
      - .env.local
    container_name: plainly_app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
    ports:
      - "3000:3000"
      - "5555:5555" # for prisma studio
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm install && pnpm prisma db push && pnpm run dev"

volumes:
  db-data:
